/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tenny_myapplication1_GLJniLib */

#ifndef _Included_com_example_tenny_myapplication1_GLJniLib
#define _Included_com_example_tenny_myapplication1_GLJniLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tenny_myapplication1_GLJniLib
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_tenny_myapplication1_GLJniLib_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_tenny_myapplication1_GLJniLib
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_tenny_myapplication1_GLJniLib_create
  (JNIEnv *, jobject);

/*
 * Class:     com_example_tenny_myapplication1_GLJniLib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_tenny_myapplication1_GLJniLib_step
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
