/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tenny_myapplication1_GLJniLib_RefreshListener */

#ifndef _Included_com_example_tenny_myapplication1_GLJniLib_RefreshListener
#define _Included_com_example_tenny_myapplication1_GLJniLib_RefreshListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
